/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FlashKeeperInterface extends ethers.utils.Interface {
  functions: {
    "WithdrawBalance()": FunctionFragment;
    "borrowCallback(address)": FunctionFragment;
    "claim(address,uint256,uint256,bytes)": FunctionFragment;
    "delegateCall(address,bytes)": FunctionFragment;
    "doBorrow(address[])": FunctionFragment;
    "executeArbitrage()": FunctionFragment;
    "executeOperation(address,uint256,uint256,bytes)": FunctionFragment;
    "getEstimatedETHForToken(uint256,address)": FunctionFragment;
    "withdrawTokens(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "WithdrawBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowCallback",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "doBorrow", values: [string[]]): string;
  encodeFunctionData(
    functionFragment: "executeArbitrage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeOperation",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEstimatedETHForToken",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "WithdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doBorrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeArbitrage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEstimatedETHForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export class FlashKeeper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FlashKeeperInterface;

  functions: {
    WithdrawBalance(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "WithdrawBalance()"(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    borrowCallback(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "borrowCallback(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claim(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(address,uint256,uint256,bytes)"(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    delegateCall(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "delegateCall(address,bytes)"(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    doBorrow(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "doBorrow(address[])"(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    executeArbitrage(overrides?: Overrides): Promise<ContractTransaction>;

    "executeArbitrage()"(overrides?: Overrides): Promise<ContractTransaction>;

    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getEstimatedETHForToken(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "getEstimatedETHForToken(uint256,address)"(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    withdrawTokens(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawTokens(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  WithdrawBalance(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "WithdrawBalance()"(
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  borrowCallback(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "borrowCallback(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claim(
    _to: string,
    _earningsToDate: BigNumberish,
    _nonce: BigNumberish,
    _signature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(address,uint256,uint256,bytes)"(
    _to: string,
    _earningsToDate: BigNumberish,
    _nonce: BigNumberish,
    _signature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  delegateCall(
    to: string,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "delegateCall(address,bytes)"(
    to: string,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  doBorrow(
    tokens: string[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "doBorrow(address[])"(
    tokens: string[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  executeArbitrage(overrides?: Overrides): Promise<ContractTransaction>;

  "executeArbitrage()"(overrides?: Overrides): Promise<ContractTransaction>;

  executeOperation(
    _reserve: string,
    _amount: BigNumberish,
    _fee: BigNumberish,
    _params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeOperation(address,uint256,uint256,bytes)"(
    _reserve: string,
    _amount: BigNumberish,
    _fee: BigNumberish,
    _params: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getEstimatedETHForToken(
    _tokenAmount: BigNumberish,
    ERC20Token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getEstimatedETHForToken(uint256,address)"(
    _tokenAmount: BigNumberish,
    ERC20Token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  withdrawTokens(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawTokens(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    WithdrawBalance(overrides?: CallOverrides): Promise<void>;

    "WithdrawBalance()"(overrides?: CallOverrides): Promise<void>;

    borrowCallback(token: string, overrides?: CallOverrides): Promise<void>;

    "borrowCallback(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claim(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(address,uint256,uint256,bytes)"(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    delegateCall(
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "delegateCall(address,bytes)"(
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    doBorrow(tokens: string[], overrides?: CallOverrides): Promise<void>;

    "doBorrow(address[])"(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    executeArbitrage(overrides?: CallOverrides): Promise<void>;

    "executeArbitrage()"(overrides?: CallOverrides): Promise<void>;

    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getEstimatedETHForToken(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getEstimatedETHForToken(uint256,address)"(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    withdrawTokens(token: string, overrides?: CallOverrides): Promise<void>;

    "withdrawTokens(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    WithdrawBalance(overrides?: PayableOverrides): Promise<BigNumber>;

    "WithdrawBalance()"(overrides?: PayableOverrides): Promise<BigNumber>;

    borrowCallback(token: string, overrides?: Overrides): Promise<BigNumber>;

    "borrowCallback(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claim(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claim(address,uint256,uint256,bytes)"(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    delegateCall(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "delegateCall(address,bytes)"(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    doBorrow(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "doBorrow(address[])"(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    executeArbitrage(overrides?: Overrides): Promise<BigNumber>;

    "executeArbitrage()"(overrides?: Overrides): Promise<BigNumber>;

    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getEstimatedETHForToken(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEstimatedETHForToken(uint256,address)"(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawTokens(token: string, overrides?: Overrides): Promise<BigNumber>;

    "withdrawTokens(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WithdrawBalance(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "WithdrawBalance()"(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    borrowCallback(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "borrowCallback(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claim(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(address,uint256,uint256,bytes)"(
      _to: string,
      _earningsToDate: BigNumberish,
      _nonce: BigNumberish,
      _signature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    delegateCall(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "delegateCall(address,bytes)"(
      to: string,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    doBorrow(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "doBorrow(address[])"(
      tokens: string[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    executeArbitrage(overrides?: Overrides): Promise<PopulatedTransaction>;

    "executeArbitrage()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    executeOperation(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeOperation(address,uint256,uint256,bytes)"(
      _reserve: string,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _params: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getEstimatedETHForToken(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEstimatedETHForToken(uint256,address)"(
      _tokenAmount: BigNumberish,
      ERC20Token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawTokens(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawTokens(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
